### ISSUE TITLE
`render_label()` not working with matplotlib 3.9.x

### ISSUE THREAD

**Issue by ktpolanski** [stardist/stardist#272]
First off, thank you for the fantastic package! I have nothing but the best to say about it, and it runs super smoothly even without GPU. It would appear that matplotlib deprecated and subsequently removed one of the functions that you're using, providing detail below.

**Describe the bug**
Matplotlib appears to have deprecated `cm.get_cmap()`. Running `cm.get_cmap()` in 3.8.x produces the following warning:

```
<stdin>:1: MatplotlibDeprecationWarning: The get_cmap function was deprecated in Matplotlib 3.7 and will be removed two minor releases later. Use ``matplotlib.colormaps[name]`` or ``matplotlib.colormaps.get_cmap(obj)`` instead.
```

True to this message, matplotlib 3.9.x no longer has `cm.get_cmap()` and running StarDist's `render_label()` produces an error.

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jovyan/my-conda-envs/b2c_wat/lib/python3.10/site-packages/stardist/plot/render.py", line 84, in render_label
    cmap_img = cm.get_cmap(cmap_img) if isinstance(cmap_img, str) else cmap_img
AttributeError: module 'matplotlib.cm' has no attribute 'get_cmap'
```

**To reproduce**
```python
from stardist.models import StarDist2D

model = StarDist2D.from_pretrained('2D_versatile_fluo')

from stardist.data import test_image_nuclei_2d
from stardist.plot import render_label
from csbdeep.utils import normalize
import matplotlib.pyplot as plt

img = test_image_nuclei_2d()

labels, _ = model.predict_instances(normalize(img))

rendered = render_label(labels, img=img)
```

**Expected behavior**
Not crashing.

**Data and screenshots**
Not applicable.

**Environment (please complete the following information):**
 - StarDist version 0.9.1
 - matplotlib version 3.9.0

no other versions feel pertinent

**Comment by ktpolanski** [comment]
On a related note, a heads up that StarDist does not work with numpy 2.x

**Comment by uschmidt83** [comment]
Hi @ktpolanski, thanks for raising this issue and sorry for not replying sooner!

I just merged @bentaculum's [PR](https://github.com/stardist/stardist/pull/278), which should fix the issue.
